//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.17626
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsContactsBirthday.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsContactsBirthday.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        internal static string ApplicationMenuItemExit {
            get {
                return ResourceManager.GetString("ApplicationMenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir les anniversaires.
        /// </summary>
        internal static string ApplicationMenuItemShowBirthday {
            get {
                return ResourceManager.GetString("ApplicationMenuItemShowBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher la notification.
        /// </summary>
        internal static string ApplicationMenuItemShowNotification {
            get {
                return ResourceManager.GetString("ApplicationMenuItemShowNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas d&apos;anniversaire à venir..
        /// </summary>
        internal static string ApplicationNotificationTextNoBirthday {
            get {
                return ResourceManager.GetString("ApplicationNotificationTextNoBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} aura {1} ans aujourd&apos;hui..
        /// </summary>
        internal static string ApplicationNotificationTextTodayBirthday {
            get {
                return ResourceManager.GetString("ApplicationNotificationTextTodayBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} aura {1} an aujourd&apos;hui..
        /// </summary>
        internal static string ApplicationNotificationTextTodayOneYear {
            get {
                return ResourceManager.GetString("ApplicationNotificationTextTodayOneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} aura {1} ans le {2}/{3}..
        /// </summary>
        internal static string ApplicationNotificationTextWeekBirthday {
            get {
                return ResourceManager.GetString("ApplicationNotificationTextWeekBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} aura {1} an le {2}/{3}..
        /// </summary>
        internal static string ApplicationNotificationTextWeekOneYear {
            get {
                return ResourceManager.GetString("ApplicationNotificationTextWeekOneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows Contacts Birthday.
        /// </summary>
        internal static string ApplicationNotificationTitle {
            get {
                return ResourceManager.GetString("ApplicationNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon NotificationIcon {
            get {
                object obj = ResourceManager.GetObject("NotificationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
